apps/admin/trancation/urls.py
from django.conf.urls import url

from apps.admin.trancation import views

urlpatterns = [
    url(r'^product-price/', views.product_price, name='product_price'),
    url(r'^add-product-price/', views.add_product_price, name='add_product_price'),
    url(r'^add-product-price-admin/', views.add_product_price_super_admin, name='add_product_price_super_admin'),
    url(r'^edit-product-price/(?P<id>\d+)/$', views.edit_product_price, name='edit_product_price'),
    url(r'^delete-product-price/', views.delete_product_price, name='delete_product_price'),
    url(r'^search-product-price/', views.search_product_price, name='search_product_price'),

    url(r'^order/', views.order, name='order'),
    url(r'^add-order/', views.add_order, name='add_order'),
    url(r'^add-order-admin/', views.add_order_super_admin, name='add_order_super_admin'),
    url(r'^order-detail/(?P<id>\d+)/$', views.order_show, name='order_show'),
    url(r'^delete-order/', views.delete_order, name='delete_order'),
    url(r'^search-order/$', views.search_order, name='search_order'),

    url(r'^add-order-product/(?P<id>\d+)/$', views.add_order_product, name='add_order_product'),
    url(r'^edit-order-product/(?P<id>\d+)/$', views.edit_order_product, name='edit_order_product'),
    url(r'^select-brand-product/$', views.select_brand_product, name='select_brand_product'),
    url(r'^delete-order-product/$', views.delete_order_product, name='delete_order_product'),

]

klik_tukang/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
# from django.contrib import admin
# from apps.api.v1.users.views import home
# from rest_framework.authtoken.views import obtain_auth_token

from apps.users_authentication import views

urlpatterns = [
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^admin/', include('apps.admin.delivery_man.urls', namespace='admin_delivery_man')),
    url(r'^admin/', include('apps.admin.customers.urls', namespace='admin_customers')),
    url(r'^admin/', include('apps.admin.dashboard.urls', namespace='admin_dashboard')),
    url(r'^admin/', include('apps.admin.users_management.urls', namespace='admin_users_management')),
    url(r'^admin/', include('apps.admin.trancation.urls', namespace='admin_trancation')),
    url(r'^api/', include('apps.api.v1.users.urls')),
    url(r'^api/', include('apps.api.v1.product_price.urls')),
    url(r'^api/', include('apps.api.v1.transaction.urls')),
    url(r'^api-token-auth/', views.ObtainExpiringAuthToken.as_view()),
    url(r'^login/', views.user_login, name='login'),
    url(r'^accounts/logout/', 'django.contrib.auth.views.logout', {'next_page': '/login'}, name='logout'),
    url(r'^registration-customer/', views.RegistrationCustomerView.as_view()),

]
#
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

apps/admin/trancation/forms.py
from django import forms

from apps.admin.customers.models import Customer
from apps.admin.users_management.models import City
from .models import ProductPrice, Order, ProductOrder, AdminCustom

valid_time_formats = ['%H:%M %p']
APPROVAL_CHOICES = (
    (u'Awaiting', u'Awaiting'),
    (u'Progress', u'Progress'),
    (u'Done', u'Done'),
)


class SearchForm(forms.Form):
    q = forms.CharField()


class ProductPriceForm(forms.ModelForm):
    brand = forms.CharField()
    image = forms.ImageField()
    price = forms.DecimalField()

    class Meta:
        model = ProductPrice
        fields = ('brand', 'image', 'price',)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ProductPriceForm, self).__init__(*args, **kwargs)

    def clean(self):
        cleaned_data = self.cleaned_data
        admin = AdminCustom.objects.get(id=self.request.user.user_admin.id)
        existing = ProductPrice.objects.filter(brand=cleaned_data['brand'], admin=admin
                                               ).count()
        if existing > 0:
            raise forms.ValidationError({'brand': 'Brand musbe uniqe'})


class ProductPriceSuperAdminForm(forms.ModelForm):
    brand = forms.CharField()
    image = forms.ImageField()
    price = forms.DecimalField()

    class Meta:
        model = ProductPrice
        fields = ('brand', 'image', 'price',)
        exclude = ('admin',)

    def clean(self):
        cleaned_data = self.cleaned_data
        city = self.data.get('city_name')
        print self.data
        admin = AdminCustom.objects.get(city__id=city)
        existing = ProductPrice.objects.filter(brand=cleaned_data['brand'], admin=admin
                                               ).count()
        if existing > 0:
            raise forms.ValidationError({'brand': 'Brand muse be uniqe'})


class ProductOrderForm(forms.ModelForm):
    def __init__(self, user, city, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ProductOrderForm, self).__init__(*args, **kwargs)
        self.initial['brand'] = 'default value'

        admin = AdminCustom.objects.get(city__name_city=city)
        try:
            brand_select = forms.ChoiceField(
                choices=([(i.brand, i.brand) for i in ProductPrice.objects.filter(admin_id=user.user_admin.id)]))
        except Exception:
            brand_select = forms.ChoiceField(
                choices=([(i.brand, i.brand) for i in ProductPrice.objects.filter(admin_id=admin)]))

        self.fields['brand'] = brand_select

    class Meta:
        model = ProductOrder
        fields = ('brand', 'price', 'quantity')
        exclude = ('product_order',)


class CitySuperAdminForm(forms.Form):
    city_name = forms.ModelChoiceField(queryset=City.objects.all(), )

    class Meta:
        model = City
        fields = ('city_name',)


class CityForm(forms.ModelForm):
    city_name = forms.ModelChoiceField(queryset=City.objects.all(), )

    class Meta:
        model = City
        fields = ('city_name',)


class OrderCustomerForm(forms.ModelForm):
    user_order = forms.ModelChoiceField(queryset=Customer.objects.all())  # Or whatever query you'd like
    time = forms.TimeField(input_formats=valid_time_formats)
    status = forms.ChoiceField(choices=APPROVAL_CHOICES)

    class Meta:
        model = Order
        fields = '__all__'
        exclude = ['time']
        widgets = {
            'user_order': forms.Select(attrs={'class': 'select'}),
        }


class OrderCustomerSuperAdminForm(forms.ModelForm):
    user_order = forms.ModelChoiceField(queryset=Customer.objects.all())  # Or whatever query you'd like
    time = forms.TimeField(input_formats=valid_time_formats)
    status = forms.ChoiceField(choices=APPROVAL_CHOICES)

    class Meta:
        model = Order
        fields = '__all__'
        exclude = ['time']
        widgets = {
            'user_order': forms.Select(attrs={'class': 'select'}),
        }

templates/js1.html
{#{% block js %}#}
{#    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>#}
{#    <script language="javascript">#}
{#        $('#id_brand_select').change(function() {populateCar(this)});#}
{#        $('#id_description').addClass('descriptions');#}
{#        cars = {{ order_product.cars | safe }}#}
{#        brands = {{ order_product.brands | safe}};#}
{#        prices = {{ order_product.prices | safe}};#}
{#        populateBrand();#}
{#        $("#id_car_select").empty();#}
{#        $("#id_car_select").append('<option value="" disabled selected>First select a brand</option>');#}
{#        function populateBrand() {#}
{#            $('#id_brand_select').empty();#}
{#            $("#id_brand_select").append('<option value="" disabled selected>Select your option</option>');#}
{#            $.each(brands, function(v) {#}
{#                $('#id_brand_select')#}
{#                    .append($("<option></option>")#}
{#                    .attr("value", brands[v])#}
{#                    .text(brands[v]));#}
{#            });#}
{#        }#}
{##}
{#        function populateCar(event) {#}
{#            brand = $("#id_brand_select option:selected").text();#}
{#            $("#id_car_select").empty();#}
{#            $("#id_car_select").append('<option value="" disabled selected>Select your option</option>');#}
{#            for (let [b, bcars] of Object.entries(cars)) {#}
{#                if (b == brand) {#}
{#                    //alert(b);#}
{#                    for (car in bcars) {#}
{#                        $('#id_car_select')#}
{#                            .append($("<option></option>")#}
{#                                .attr("value", bcars[car])#}
{#                                .text(bcars[car]));#}
{#                    }#}
{#                }#}
{#            }#}
{#        }#}
{##}
{#        function populatePrice(event) {#}
{#            brand = $("#id_brand_select option:selected").text();#}
{#            cosole.log(brand)#}
{#            $("#id_car_select").empty();#}
{#            $("#id_car_select").append('<option value="" disabled selected>Select your option</option>');#}
{#            for (let [b, bcars] of Object.entries(cars)) {#}
{#                if (b == brand) {#}
{#                    //alert(b);#}
{#                    for (car in bcars) {#}
{#                        $('#id_car_select')#}
{#                            .append($("<option></option>")#}
{#                                .attr("value", bcars[car])#}
{#                                .text(bcars[car]));#}
{#                    }#}
{#                }#}
{#            }#}
{#        }#}
{#    </script>#}
{#{% endblock %}#}


{% block js %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script>
        $(function () {
            {#           $("#id_brand").change(function () {#}
            {#                var brand = $("#id_brand").val();#}
            {#                var price = $('#id_price option[value="' + brand + '"]').val();#}
            {#                console.log(price)#}
            {#                $('#id_price option[value="' + price + '"]').prop('selected', true);#}
            {##}
            {#            })#}

            $("#id_brand").change(function () {
                var brand = $("#id_brand").val();
                var id_order_product = $("#id_order_product").val();
                $.ajax({
                    type: 'POST',
                    url: "{% url 'admin_trancation:select_brand_product' %}",
                    data: {"brand": brand,"id_order_product":id_order_product,  csrfmiddlewaretoken: '{{ csrf_token }}',},
                    dataType: 'json',
                    success: function (data) {

                        $("#id_price").val(data.brand_price);
                    }
                });

            });


        })


    </script>

{% endblock %}